#!/bin/zsh

# This file has a purpose of only storing configuration.

# Database configuration
DATABASE_NAME="booksmaster"
DATABASE_USER="root"
DATABASE_PASSWORD=""
DATABASE_HOST="localhost"

# Migration configuration
MIGRATIONS_DIR="app/migrations"
MIGRATION_PREFIX="migration_"

# Server Configuration
PORT=8080
ENVIRONMENT="development"

echo "WILL BE DEPRECATED SOON! Please use cli file instead."
